### ISSUE TITLE
how do i play this game from the CD 

### ISSUE THREAD

**Issue by neighbor00neighbor0** [rovitotv/SensorCraft#1]

**Comment by rovitotv** [comment]
Yes we are here to help! The latest release can be downloaded here which is [version 1.5](https://github.com/rovitotv/SensorCraft/releases/latest)

After you download SensorCraft you need a version of python to run it with. Python is free software we recommend Enthought Canopy Express which you can download [here](https://store.enthought.com/downloads/#default) or install from the CD in the Enthought directory. Pick your appropriate operating system and install the normal way for your operating system. After you get Enthought installed you have to unzip SensorCraft into a folder on your hard disk. Next run Enthought Canopy then from the Enthought python shell enter the command:

`cd DirectoryNameOfSensorCraft/code`

Don't forget to add the code directory onto the cd command. Next edit one of the exercise files with the command:

`edit 04_play_with_gravity.py`

Then click the Green Arrow button to run the program. Walk through the html files for each of the programming exercises.

Please let us know if you need additional help. We plan to post YouTube videos of the install process and will post on the front page of this site as soon as we get back from USA Science Festival in DC. Thanks!

**Comment by rovitotv** [comment]
Here is a youtube video that I created showing you how to install the required software and run the examples.  I hope this helps!

[SensorCraft Install and Run YouTube video](https://youtu.be/C9n1bS54AIw)
