### ISSUE TITLE
ImportError: cannot import name gl_info 

### ISSUE THREAD

**Issue by mistertbone** [rovitotv/SensorCraft#17]
When trying to run the program i receive this error.
ImportError: cannot import name gl_info 

How can I fix this?

**Comment by rovitotv** [comment]
What operating system and version are you using?  Windows, Mac OS X, or Linux

If Linux what distro do you have?

While running Enthought at the bottom of the screen in the command window type the following:

``` python
import pyglet
print(pyglet.version)
```

You should haver version 1.2.4 if you do not please issue the following command in the Canopy python window:

``` bash
! pip install pyglet --upgrade
```

See the install section of the [SensorCraft guide](http://sensorcraft.readthedocs.io/en/stable/intro.html#install)

Please let us know what results you get, thank you for trying our game!

**Comment by mistertbone** [comment]
Thank you for your reply.

I am using Windows 10 64 bit.

I ran the import piglet command and the print command.   I was not at the version you have listed and so I did the upgrade command.

This installed V1.2.4.

I received a message back that said I am using pip version 8.1.1 and should upgrade to 8.1.2.

After running this upgrade it appears to be working.  I had a Pyglet window open that was just white with nothing in it one time, but when I closed everything and restarted Canopy, the game opened fine.

Thank you for your help.  If we have more problems can I contact you through this email?

Thanks again,

Jeff,

**Comment by rovitotv** [comment]
I am glad you got SensorCraft working and I hope you enjoy playing our game!!!!  Sorry for any frustration the original error you received might have caused you.  Upgrading pyglet most likely fixed the problem you don't need to upgrade pip but if you did that is ok.  

> I had a Pyglet window open that was just white with nothing in it one time, but when I closed everything > and restarted Canopy, the game opened fine.

Make sure you change directory into the SensorCraft directory.  Usually use the command:

``` bash
cd ~/SensorCraft/code
```

The command above assumes that you installed SensorCraft in your home directory.  Between runs of SensorCraft you have to remember to restart the python kernel which is done by selecting the run menu then "restart kernel".  See [restart of the python kernel](http://sensorcraft.readthedocs.io/en/stable/intro.html#restart-of-the-python-kernel) in the documentation.

> Thank you for your help.  If we have more problems can I contact you through this email?

The best way to get support is to create a new issue on the [github site for SensorCraft](https://github.com/rovitotv/SensorCraft/issues) that way other people in the community can see past answers and get support.  Please let us know if you have any additional problems or comments.  Thanks!
