### ISSUE TITLE
how do I download the game from the website? I've installed the GitHub software, but I can't download the game. 

### ISSUE THREAD

**Issue by nightphoenixfire** [rovitotv/SensorCraft#2]
My computer doesn't have a disk reader. Can someone please help me?

**Comment by rovitotv** [comment]
Yes we are here to help!  The latest release can be downloaded [here](https://github.com/rovitotv/SensorCraft/releases/latest) which is V1.5.

After you download SensorCraft you need a version of python to run it with.  Python is free software we recommend Enthought Canopy Express which you can [download here](https://store.enthought.com/downloads/#default).  Pick your appropriate operating system and install the normal way for your operating system.  After you get Enthought installed you have to unzip SensorCraft into a folder.  Next run Enthought Canopy then from the Enthought python shell enter the command:

`cd DirectoryNameOfSensorCraft/code`

Don't forget to add the code directory onto the cd command.  Next edit one of the exercise files with the command: 

`edit 04_play_with_gravity.py`

Then click the Green Arrow button to run the program.  Walk through the html files for each of the programming exercises.  

Please let us know if you need additional help.  We plan to post YouTube videos of the install process and will post on the front page of this site as soon as we get back from USA Science Festival in DC.  Thanks!

**Comment by rovitotv** [comment]
Here is a youtube video that I created showing you how to install the required software and run the examples.  I hope this helps!

[SensorCraft Install and Run YouTube video](https://youtu.be/C9n1bS54AIw)
